### ISSUE TITLE
Linkerd apps 

### ISSUE THREAD

**Issue by saiyam1814** [civo/kubernetes-marketplace#182]
@JasonMorgan So right now there are three apps in the production can we have Plans for them and have only single app ? then in the install.sh based on the value of plan we run the respective helm install.

So we can have something like this in the PLANS section 
```
plans:
  - label: "Linkerd"
    configuration:
      LINKERD
        value: linkerd
  - label: "linkerd+jaeger"
    configuration:
      LINKERD
        value: linkerdjaeger
  - label: "Linkerd+viz"
    configuration:
      LINKERD:
        value: linkerdviz
```

now in the install.sh we can have below

```
#!/bin/bash

curl -sL https://run.linkerd.io/install | sh

export PATH=$PATH:$HOME/.linkerd2/bin
linkerd check --pre && linkerd install | kubectl apply -f -
if [$LINKERD == "linkerd"]
then
   linkerd check || exit 1
elif [ $LINKERD == "linkerdjaeger" ] 
then 
    linkerd check && linkerd jaeger install | kubectl apply -f -
    linkerd check || exit 1
else 
    linkerd check && linkerd viz install | kubectl apply -f -    
    linkerd check || exit 1
fi 

```
In this way, we can have options for installations within the same application 

@andyjeffries thoughts ?
