### ISSUE TITLE
Are Linkerd plans correct?

### ISSUE THREAD

**Issue by zulh-civo** [civo/kubernetes-marketplace#201]
This issue is a:
* [x] Bug Report
* [ ] Enhancement suggestion
* [ ] Feature request

## Bug Reports
- Expected behaviour
  When running `$ civo kubernetes applications ls` CLI command, I'm expecting a list of all Civo Marketplace apps with _Plans_ column contains values like _5GB, 10GB, 15GB_.

- Encountered behaviour
  What I noticed is, Linkerd plans are strings with the following values: `Linkerd Minimal, Linkerd & Jaeger, Linkerd with Dashboard, Linkerd with Dashboard & Jaeger`.

  Is this a mistake?

  Because of this, the _Plans_ column became too wide and causing double rows problem to other apps when the viewport is small e.g. a normal laptop screen (not an external display).

  If this bug report is incorrect/false alarm, feel free to close this.

- The steps to recreate the behaviour that you are reporting
  Run `$ civo kubernetes applications ls` CLI command

  <img width="1435" alt="Screenshot 2021-05-18 at 1 31 27 PM" src="https://user-images.githubusercontent.com/75463191/118595504-c83c9100-b7dd-11eb-9932-b715aa1534ee.png">

**Comment by zulh-civo** [comment]
FYI @JasonMorgan @saiyam1814

**Comment by saiyam1814** [comment]
Hi Zulh, yes the plans are correct, this is the new use case that has been implemented for Linkerd and also will be implemented for Kyverno. This has opened the flexibility for different installs.

**Comment by zulh-civo** [comment]
I thought the Plans is just for storage size...

This can break Marketplace v2 because it expects the Plans are storage sizes e.g. 5GB, 10GB and etc -- which then get parse to int for processing.

Can we call this type of new plans something else e.g. Vendor Plans and leave the storage size Plans as is?

@saiyam1814

**Comment by saiyam1814** [comment]
So this is string and parsed as string, and is used in the same way inside install.sh or app.yaml 
should not make a difference. 
But I agree that we should be more explicit in documentation for plans and define these use-cases

**Comment by zulh-civo** [comment]
What I'm trying to say here is, we need a way to differentiate storage size plans (which then will be parsed as int) VS non-storage size plans (like what's inside this Linkerd app).

Right now, marketplace v2 assume all values under the Plans are storage size plans. Installing this Linkerd app (with its current manifest.yaml file) on marketplace v2 will fail. Moving forward, I'd like to propose this structure instead:

```yaml
name: Linkerd
version: Latest
maintainer: hello@buoyant.io
description: Linkerd is a service mesh, giving you runtime debugging, observability, reliability, and security.
url: https://linkerd.io
category: architecture
vendor_plans: <----------- this key
  - label: "Linkerd Minimal"
    configuration:
      LINKERD:
        value: linkerd
  - label: "Linkerd & Jaeger"
    configuration:
      LINKERD:
        value: linkerdjaeger
  - label: "Linkerd with Dashboard"
    configuration:
      LINKERD:
        value: linkerdviz
  - label: "Linkerd with Dashboard & Jaeger"
    configuration:
      LINKERD:
        value: theworks
```
