### ISSUE TITLE
Addition of K8S dashboard

### ISSUE THREAD

**Issue by morganlaneap** [civo/kubernetes-marketplace#26]
This issue is a:
[ ] Bug Report
[x] Enhancement suggestion
[ ] Feature request

## Enhancement suggestions / feature requests
If you are requesting an enhancement to a feature already present, or a new feature, please outline below the feature you would like to see, and how it would benefit you and the wider Civo Kubernetes userbase:

I have been wondering about the possibility of getting the K8S dashboard installed and running as an extension on the marketplace. It's quite straight forward to install, the only issues is the proxy that is required to access it. I can create the marketplace addon to install the dashboard, but how feasible is it to get the proxy listening on the public IP address or elsewhere? 

This link is a good resource regarding the dashboad: https://www.replex.io/blog/how-to-install-access-and-add-heapster-metrics-to-the-kubernetes-dashboard

**Comment by andyjeffries** [comment]
So rather than the proxy, could you not just use Traefik to create an authenticated ingress route for it? Something like this Prometheus example:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: prometheus-dashboard
 namespace: monitoring
 annotations:
   kubernetes.io/ingress.class: traefik
   traefik.ingress.kubernetes.io/auth-type: "basic"
   traefik.ingress.kubernetes.io/auth-secret: "mysecret"
spec:
 rules:
 - host: dashboard.prometheus.example.com
   http:
     paths:
     - backend:
         serviceName: prometheus
         servicePort: 9090
```

When our new firewall code goes live, we'll make it easier to firewall off the port, only opening it to IPs you choose, but for now this may work OK. You could use the [Customising](https://github.com/civo/kubernetes-marketplace#customising) feature of marketplace apps to set a long random password (say 20-30 chars).
