### ISSUE TITLE
Ambassador example not working

### ISSUE THREAD

**Issue by exocode** [civo/kubernetes-marketplace#282]
This issue is a:
* [ X] Bug Report

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below: 

@milindchawre 

## Bug Reports
If the issue is a Bug Report, please detail the following:

- Cluster with Ambassador installed
- Follow the "Getting started" link for Ambassador in the "installed applications" section of the Marketplace App.
  - Quickstart guide for ambassador edge stack. Which brings me there: https://www.getambassador.io/docs/edge-stack/latest/tutorials/getting-started/
- copy/paste the very first command in "STEP 2" (because step 1 is already done by installing the Marketplace app) ***
- 

*** command 
```
kubectl apply -f - <<EOF
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: edge-stack-listener-8080
  namespace: ambassador
spec:
  port: 8080
  protocol: HTTP
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: edge-stack-listener-8443
  namespace: ambassador
spec:
  port: 8443
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL
EOF

```

Which fails with that error: 

```shell
unable to recognize "listener.yml": no matches for kind "Listener" in version "getambassador.io/v3alpha1"
unable to recognize "listener.yml": no matches for kind "Listener" in version "getambassador.io/v3alpha1"```


I am quite sure, that this has to do with the Version at Marketplace which is `1.13.10` and the linked one which is `2.x`

So either linking the right Docs or updating the marketplace app will probably solve the problem.
