### ISSUE TITLE
Allow applications to use resources from other applications

### ISSUE THREAD

**Issue by andyjeffries** [civo/kubernetes-marketplace#6]
@alejandrojnm is trying to implement [Hasura](https://hasura.io) as a marketplace application, but it requires a PostgreSQL database. 

**First thoughts**

My original thoughts were to allow passing of configuration items from one application to another. e.g.

```
configuration:
  DB_USERNAME:
    label: "Access key"
    value: "CIVO:APPLICATION:POSTGRES:ROOT_USER_NAME"
```

However, I don't think it's nice if Application B can pull the authentication details from Application A.

**New plan**

So now I'm thinking about a slightly nicer interface where applications can provide `resources`. So PostgreSQL would define something like this in the `app.yaml`:

```
resources:
  provide:
    - database
```

and it would have a new `resource.sh` script which takes two command line positional parameters, the action of either `create` or `delete` (for later uninstalling) and a name, which will by default by the application followed by the resource name lowercased. It will output a single line containing the details required to access the resource (usually a URL):

```
$ resource.sh create hasura-postgres_db
postgres://RANDOM_USERNAME:RANDOM_PASSWORD@postgres.svc:5432/hasura-postgres_db
```

Applications that require a database would request one by doing:

```
dependencies:
  - postgres
resources:
  require:
    POSTGRES_DB:
      application: postgres
      resource: database
```

The output of the `resource.sh` script would then be injected in to $POSTGRES_DB the same as if it had been defined as a `configuration` setting normally.

Would welcome any feedback from anyone writing or thinking about writing marketplace applications.
